sudo: required
services:
  - docker

before_install:
  - docker build -t donol17/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true donol17/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "b6c17246-9ecb-4362-b103-36306717c102"
  app: docker-react
  on: master
